<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE log [
<!ELEMENT log (Page?, Visit*, Visitor?)>
<!ELEMENT Page (pid, url)?>
<!ELEMENT pid (#PCDATA)>
<!ELEMENT url (#PCDATA)>
<!ELEMENT Visit (tid, vdate, vtime)*>
<!ELEMENT tid (#PCDATA)>
<!ELEMENT vdate (#PCDATA)>
<!ELEMENT vtime (#PCDATA)>
<!ELEMENT Visitor (vid, ip)?>
<!ELEMENT vid (#PCDATA)>
<!ELEMENT ip (#PCDATA)>
]>
<log>
  <Page>
    <pid>100</pid>
    <url>"http://artificium.us/lessons/l101.html"</url>
    <pid>200</pid>
    <url>"http://articificum.us/courses/cs1100.html"</url>
    <pid>300</pid>
    <url>"http://google.com"</url>
    <pid>400</pid>
    <url>"http://yahoo.com"</url>
    <pid>500</pid>
    <url>"http://youtube.com"</url>
  </Page>
  <Visit>
    <tid>1</tid>
    <vdate>"2021-09-30"</vdate>
    <vtime>"20:03:44"</vtime>
    <tid>2</tid>
    <vdate>"2021-08-31"</vdate>
    <vtime>"08:03:34"</vtime>
    <tid>3</tid>
    <vdate>"2022-11-20"</vdate>
    <vtime>"09:04:24"</vtime>
    <tid>4</tid>
    <vdate>"2022-11-21"</vdate>
    <vtime>"10:05:14"</vtime>
    <tid>5</tid>
    <vdate>"2022-11-22"</vdate>
    <vtime>"11:06:04"</vtime>
  </Visit>
  <Visitor>
    <vid>101</vid>
    <ip>"165.11.33.45"</ip>
    <vid>102</vid>
    <ip>"214.178.135.106"</ip>
    <vid>103</vid>
    <ip>"127.211.61.131"</ip>
    <vid>104</vid>
    <ip>"67.203.122.134"</ip>
    <vid>105</vid>
    <ip>"102.70.111.54"</ip>
  </Visitor>
</log>
